export const CATEGORIES = [
  { id: "primary", label: "Primary", icon: "person" },
  { id: "transactions", label: "Transactions", icon: "cart" },
  { id: "updates", label: "Updates", icon: "news" },
  { id: "promotions", label: "Promotions", icon: "megaphone" },
];

export const MAILBOX_GROUPS = [
  {
    label: "Favorites",
    items: [
      { id: "inbox", label: "Inbox", icon: "inbox" },
      { id: "flagged", label: "Flagged", icon: "flag" },
      { id: "drafts", label: "Drafts", icon: "draft" },
      { id: "sent", label: "Sent", icon: "sent" },
    ],
  },
  { label: "Smart Mailboxes", items: [] },
  {
    label: "Mail Account",
    items: [
      { id: "important", label: "Important", icon: "flag" },
      { id: "account-inbox", label: "Inbox", icon: "inbox" },
      { id: "account-drafts", label: "Drafts", icon: "draft" },
      { id: "account-sent", label: "Sent", icon: "sent" },
      { id: "junk", label: "Junk", icon: "junk" },
      { id: "trash", label: "Trash", icon: "trash" },
      { id: "archive", label: "Archive", icon: "archive" },
    ],
  },
];

export const INITIAL_MESSAGES = [
  {
    id: "learning",
    mailbox: "inbox",
    category: "primary",
    sender: "Learning App",
    time: "19:46",
    subject: "Continue your lesson today",
    preview: "Start one short lesson and keep your learning streak alive.",
    body: "Your next lesson is ready. Take a few minutes to keep your learning streak going.",
    to: "user@example.com",
    unread: true,
    flagged: false,
  },
  {
    id: "security",
    mailbox: "inbox",
    category: "primary",
    sender: "Account Service",
    time: "17:16",
    subject: "Review your account settings",
    preview: "Here are a few tips for keeping your account secure.",
    body: "Review your account settings and confirm that your recovery details are current.",
    to: "user@example.com",
    unread: false,
    flagged: false,
  },
  {
    id: "social",
    mailbox: "inbox",
    category: "updates",
    sender: "Social Network",
    time: "19:07",
    subject: "Three people viewed your profile",
    preview: "Your profile is getting attention from people in your industry.",
    body: "Three people viewed your profile this evening. Open the activity page to see more details.",
    to: "user@example.com",
    unread: true,
    flagged: false,
  },
  {
    id: "payment",
    mailbox: "inbox",
    category: "transactions",
    sender: "Demo Bank",
    time: "13:07",
    subject: "Internet transaction journal",
    preview: "Your mobile banking transaction was successful.",
    body: "The example transaction was completed successfully. Review the attached transaction details in your banking app.",
    to: "user@example.com",
    unread: true,
    flagged: true,
  },
  {
    id: "investment",
    mailbox: "inbox",
    category: "promotions",
    sender: "Invest App",
    time: "15:39",
    subject: "Low-risk investment insights",
    preview: "Explore a few low-risk options for your monthly savings.",
    body: "This promotional message contains example investment information only.",
    to: "user@example.com",
    unread: false,
    flagged: false,
  },
  {
    id: "may-heart-proposal",
    mailbox: "important",
    category: "primary",
    sender: "From the depths of my heart",
    senderEmail: "myheart@gmail.com",
    time: "Today",
    subject: "A Moment I’ve Long Been Waiting For",
    preview: "There is one question I’ve been wanting to ask you.",
    body: "# A Question I’ve Been Waiting to Ask\n\nHey,\n\nI’ve been holding onto this question for quite a while.\n\nNot because I was ever unsure about how I feel, but because I wanted to wait for the right moment—the moment when I could finally ask you this with all the sincerity in my heart.\n\nSomewhere along the way, you became more than just someone I care about. You became someone I look forward to talking to, someone who makes ordinary days feel a little brighter, and someone whose presence has slowly become one of my favorite parts of life.\n\nAnd after all the moments we’ve shared—the conversations, the laughter, the difficult days, the random little things, and everything in between—I realized that I don’t want to only be someone who stays close to you.\n\nI want to be someone who gets to choose you openly.\n\nSomeone who gets to be there for your happiest days and your hardest ones. Someone you can laugh with, grow with, rest with, and hopefully, one day, call home in your own way.\n\nI can’t promise that I will always love you perfectly. I’ll probably make mistakes, and there will always be things I still need to learn. But I can promise that I’ll keep learning how to love you better—gently, honestly, patiently, and wholeheartedly.\n\nSo after keeping this question in my heart for so long, I think this is finally the moment I’ve been waiting for.\n\n**May I be your boyfriend?**\n\nWhatever your answer is, I want it to come completely from your heart. There’s no pressure, and you don’t have to answer before you’re ready.\n\nBut when you are ready...\n\nIf your answer is **YES**, there’s only one place where I really hope to hear it:\n\n**[💗 Yes, I want you to be my boyfriend](https://wa.me/6285155333451?text=Iyaaa%20Gantengggg%20akuuuu%20mauuuuu)**\n\nAnd if your answer is **NO**, you can tell me on Discord. I’ll understand, and I’ll respect your answer just the same.\n\nBecause more than anything, I want your answer to be something you truly choose—not something you ever feel pressured to give me.\n\nBut between us... I really, really hope that little WhatsApp notification comes from you. 🤍\n\nWith all my heart,\nMay Heart",
    to: "stasyamyprincess@gmail.com",
    toName: "Stasya Annesty",
    unread: true,
    flagged: false,
  },
  {
    id: "account-update",
    mailbox: "account-inbox",
    category: "updates",
    sender: "Workspace App",
    time: "11:24",
    subject: "Your weekly workspace summary",
    preview: "Five pages changed and two comments are waiting for your reply.",
    body: "Here is your weekly workspace activity summary.",
    to: "user@example.com",
    unread: true,
    flagged: false,
  },
  {
    id: "draft-example",
    mailbox: "drafts",
    category: "primary",
    sender: "Draft",
    time: "10:12",
    subject: "Planning notes",
    preview: "A saved local draft for testing the Drafts mailbox.",
    body: "This is a local draft fixture.",
    to: "team@example.com",
    unread: false,
    flagged: false,
  },
  {
    id: "sent-example",
    mailbox: "sent",
    category: "primary",
    sender: "You",
    time: "09:40",
    subject: "Project update",
    preview: "A local sent-message fixture for the Sent mailbox.",
    body: "This is a local sent-message fixture.",
    to: "team@example.com",
    unread: false,
    flagged: false,
  },
  {
    id: "archived-example",
    mailbox: "archive",
    category: "primary",
    sender: "Archive Service",
    time: "Yesterday",
    subject: "Archived project note",
    preview: "A local archived message fixture.",
    body: "This is a local archived message fixture.",
    to: "user@example.com",
    unread: false,
    flagged: false,
  },
  {
    id: "junk-example",
    mailbox: "junk",
    category: "promotions",
    sender: "Unknown Sender",
    time: "Yesterday",
    subject: "Example junk message",
    preview: "A local junk mailbox fixture.",
    body: "This is a local junk message fixture.",
    to: "user@example.com",
    unread: true,
    flagged: false,
  },
  {
    id: "trash-example",
    mailbox: "trash",
    category: "transactions",
    sender: "Old Receipt",
    time: "Monday",
    subject: "Example deleted receipt",
    preview: "A local Trash mailbox fixture.",
    body: "This is a local Trash message fixture.",
    to: "user@example.com",
    unread: false,
    flagged: false,
  },
];

export function createInitialMessages() {
  return INITIAL_MESSAGES.map((message) => ({ ...message }));
}
