export const CATEGORIES = [
  { id: "primary", label: "Primary", icon: "person" },
  { id: "transactions", label: "Transactions", icon: "cart" },
  { id: "updates", label: "Updates", icon: "news" },
  { id: "promotions", label: "Promotions", icon: "megaphone" },
];

export const MAILBOX_GROUPS = [
  {
    label: "Favorites",
    items: [
      { id: "inbox", label: "Inbox", icon: "inbox" },
      { id: "flagged", label: "Flagged", icon: "flag" },
      { id: "drafts", label: "Drafts", icon: "draft" },
      { id: "sent", label: "Sent", icon: "sent" },
    ],
  },
  { label: "Smart Mailboxes", items: [] },
  {
    label: "Mail Account",
    items: [
      { id: "important", label: "Important", icon: "flag" },
      { id: "account-inbox", label: "Inbox", icon: "inbox" },
      { id: "account-drafts", label: "Drafts", icon: "draft" },
      { id: "account-sent", label: "Sent", icon: "sent" },
      { id: "junk", label: "Junk", icon: "junk" },
      { id: "trash", label: "Trash", icon: "trash" },
      { id: "archive", label: "Archive", icon: "archive" },
    ],
  },
];

export const INITIAL_MESSAGES = [
  {
    id: "learning",
    mailbox: "inbox",
    category: "primary",
    sender: "Learning App",
    time: "19:46",
    subject: "Continue your lesson today",
    preview: "Start one short lesson and keep your learning streak alive.",
    body: "Your next lesson is ready. Take a few minutes to keep your learning streak going.",
    to: "user@example.com",
    unread: true,
    flagged: false,
  },
  {
    id: "security",
    mailbox: "inbox",
    category: "primary",
    sender: "Account Service",
    time: "17:16",
    subject: "Review your account settings",
    preview: "Here are a few tips for keeping your account secure.",
    body: "Review your account settings and confirm that your recovery details are current.",
    to: "user@example.com",
    unread: false,
    flagged: false,
  },
  {
    id: "social",
    mailbox: "inbox",
    category: "updates",
    sender: "Social Network",
    time: "19:07",
    subject: "Three people viewed your profile",
    preview: "Your profile is getting attention from people in your industry.",
    body: "Three people viewed your profile this evening. Open the activity page to see more details.",
    to: "user@example.com",
    unread: true,
    flagged: false,
  },
  {
    id: "payment",
    mailbox: "inbox",
    category: "transactions",
    sender: "Demo Bank",
    time: "13:07",
    subject: "Internet transaction journal",
    preview: "Your mobile banking transaction was successful.",
    body: "The example transaction was completed successfully. Review the attached transaction details in your banking app.",
    to: "user@example.com",
    unread: true,
    flagged: true,
  },
  {
    id: "investment",
    mailbox: "inbox",
    category: "promotions",
    sender: "Invest App",
    time: "15:39",
    subject: "Low-risk investment insights",
    preview: "Explore a few low-risk options for your monthly savings.",
    body: "This promotional message contains example investment information only.",
    to: "user@example.com",
    unread: false,
    flagged: false,
  },
  {
    id: "account-update",
    mailbox: "account-inbox",
    category: "updates",
    sender: "Workspace App",
    time: "11:24",
    subject: "Your weekly workspace summary",
    preview: "Five pages changed and two comments are waiting for your reply.",
    body: "Here is your weekly workspace activity summary.",
    to: "user@example.com",
    unread: true,
    flagged: false,
  },
  {
    id: "draft-example",
    mailbox: "drafts",
    category: "primary",
    sender: "Draft",
    time: "10:12",
    subject: "Planning notes",
    preview: "A saved local draft for testing the Drafts mailbox.",
    body: "This is a local draft fixture.",
    to: "team@example.com",
    unread: false,
    flagged: false,
  },
  {
    id: "sent-example",
    mailbox: "sent",
    category: "primary",
    sender: "You",
    time: "09:40",
    subject: "Project update",
    preview: "A local sent-message fixture for the Sent mailbox.",
    body: "This is a local sent-message fixture.",
    to: "team@example.com",
    unread: false,
    flagged: false,
  },
  {
    id: "archived-example",
    mailbox: "archive",
    category: "primary",
    sender: "Archive Service",
    time: "Yesterday",
    subject: "Archived project note",
    preview: "A local archived message fixture.",
    body: "This is a local archived message fixture.",
    to: "user@example.com",
    unread: false,
    flagged: false,
  },
  {
    id: "junk-example",
    mailbox: "junk",
    category: "promotions",
    sender: "Unknown Sender",
    time: "Yesterday",
    subject: "Example junk message",
    preview: "A local junk mailbox fixture.",
    body: "This is a local junk message fixture.",
    to: "user@example.com",
    unread: true,
    flagged: false,
  },
  {
    id: "trash-example",
    mailbox: "trash",
    category: "transactions",
    sender: "Old Receipt",
    time: "Monday",
    subject: "Example deleted receipt",
    preview: "A local Trash mailbox fixture.",
    body: "This is a local Trash message fixture.",
    to: "user@example.com",
    unread: false,
    flagged: false,
  },
];

export function createInitialMessages() {
  return INITIAL_MESSAGES.map((message) => ({ ...message }));
}
